FROM ubuntu:16.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --yes python3-minimal python3-pip python3-dev iproute2 && \
    rm /lib/systemd/system/getty@.service

